
services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dmb_timer
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: supersecret
    volumes:
      - postgres_data:/var/lib/postgresql/data

  alembic:
    build: .
    command: alembic upgrade head
    depends_on:
      - db
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: dmb_timer
      DB_USER: bot_user
      DB_PASSWORD: supersecret
      DATABASE_URL: postgresql+psycopg2://bot_user:supersecret@db:5432/dmb_timer
    volumes:
      - .:/app
    working_dir: /app

  bot:
    build: .
    command: python bot/main.py
    depends_on:
      - db
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: dmb_timer
      DB_USER: bot_user
      DB_PASSWORD: supersecret
      DATABASE_URL: postgresql+psycopg2://bot_user:supersecret@db:5432/dmb_timer
    volumes:
      - .:/app
    working_dir: /app
    restart: always

volumes:
  postgres_data:
