"""Set is_subscribed default true

Revision ID: 9466644b3e69
Revises: b397b7d24421
Create Date: 2025-05-13 12:31:18.206341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9466644b3e69'
down_revision: Union[str, None] = 'b397b7d24421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_subscribed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_subscribed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
